# Generated by Django 3.1.1 on 2020-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='group',
            field=models.CharField(choices=[('Office', 'Office'), ('Industrial', 'Industrial'), ('Retail', 'Retail'), ('Leisure', 'Leisure')], max_length=255),
        ),
    ]
